### ISSUE TITLE
Suggestion: Movable HUD

### ISSUE THREAD

**Issue by Toxicom** [Single-sh/EpicMMOSystem#9]
# Description
I play on 1440p screen and it looks weird having the HUD just stuck there in the corner. It would be great to have an option to move it to the center of the screen. Example in the screenshots.

| Example Screenshots |
| :---: |
| **Before** |
| ![image](https://user-images.githubusercontent.com/69549795/182442360-f31a59a1-2845-4ca3-b143-40ab3d0fcbea.png) |
| **After** |
| ![image](https://user-images.githubusercontent.com/69549795/182442389-e031708b-247a-4f61-b27e-a964a109ecdd.png) |

**Comment by ConSolatory** [comment]
It's already there
Try pressing ESC and just moving the mouse around the interface

**Comment by ConSolatory** [comment]
> # Description
> I play on 1440p screen and it looks weird having the HUD just stuck there in the corner. It would be great to have an option to move it to the center of the screen. Example in the screenshots.
> 
> Example Screenshots
> **Before**
> ![image](https://user-images.githubusercontent.com/69549795/182442360-f31a59a1-2845-4ca3-b143-40ab3d0fcbea.png)
> **After**
> ![image](https://user-images.githubusercontent.com/69549795/182442389-e031708b-247a-4f61-b27e-a964a109ecdd.png)

It's already there
Try pressing ESC and just moving the mouse around the
